name: Discord Notify

on:
  push:
    branches: [ main ]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Notification
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -d "{\"content\":\"🔔 **MAJU JAYA BOT Bot Update!**\n👤 Wandi push ke ${{ github.ref_name }}\n📝 ${{ github.event.commits[0].message }}\n" \
            "${{ secrets.DISCORD_WEBHOOK }}"