name: Discord Notify

on:
  push:
    branches: [ main ]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Debug: Cek Secret
        run: |
          echo "Webhook URL length: ${#DISCORD_WEBHOOK}"
          if [ -z "$DISCORD_WEBHOOK" ]; then
            echo "ERROR: DISCORD_WEBHOOK is empty!"
            exit 1
          else
            echo "Secret loaded successfully"
          fi
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Send Discord Notification
        run: |
          curl -X POST \
          -H "Content-Type: application/json" \
          -d "{\"content\":\"🔔 **SOMRP Bot Update!**\n👤 ${{ github.actor }} push ke `${{ github.ref_name }}`\n📝 ${{ github.event.commits[0].message }}\n🔗 ${{ github.event.compare }}\"}" \
          "${{ secrets.DISCORD_WEBHOOK }}"